# Generated by Django 2.1.2 on 2018-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_pessoas'),
        ),
    ]
