# Generated by Django 2.1.2 on 2018-10-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_pessoas_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
